### ISSUE TITLE
i18n enhancements

### ISSUE THREAD

**Issue by ghost** [IdentityPython/pyFF#115]
a quick synopsis of my planned contribution:

add de locale
regard xml:lang (e.g. in mdui:DisplayName)
make locale depended on browser preferences

**Comment by peppelinux** [comment]
I'm going to add `it` locale but still have a question,
in django I use `makemessages` to get all the messages, extracted from py and html files, in a single .po file. Then `compilemessages` to get the .mo file.

What suggestions do you have to manage a good localization for pyff?
Is there any guidelines? I have to localize ra21.html template and before studying and trying things I'd like to receive some of your suggestions :) thanks a lot

**Comment by leifj** [comment]
First thing to note is that since all HTML will be removed in 2.0 (which is very soon) it is probably not worth your effort to spend time on i18n for the current UI parts of pyFF - with one exception. Adding ways to control which languages are returned in disojson responses in the api is probably still a good idea. For all other UI-related i18n contributions please refer to the spin-off projects TheIdentitySelector/thiss.io and SUNET/mdq-browser where the UX currently in pyFF has moved to.
