### ISSUE TITLE
Request for IDPSSO still has SPs in resulting file

### ISSUE THREAD

**Issue by alanbuxey** [IdentityPython/pyFF#196]
When filtering for IdP SSO only, resulting file contains SPSSO if the entity had both elements

## Code Version
1.1.2

## Expected Behavior
only IDPSSO in resulting file.

## Current Behavior
IdP and SP SSO present if the entities have both

## Steps to Reproduce

test2.rd.   (can use any Federation or eduGAIN feed which have entities with both characters)
```
- load:
   - http://md.incommon.org/InCommon/InCommon-metadata.xml incommon.pem
- select: "!//md:EntityDescriptor[md:IDPSSODescriptor]"
- xslt:
    stylesheet: tidy.xsl
- publish: /tmp/idp.xml
- stats
```

```
$ pyff test2.rd 
---
total size:     9978
selected:       3463
          idps: 3463
           sps: 2
---
```

grep SPSSO /tmp/idp.xml

$ grep SPSSO /tmp/idp.xml 
```    
    <md:SPSSODescriptor errorURL="http://cern.ch/serviceportal" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    </md:SPSSODescriptor>
    <md:SPSSODescriptor WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    </md:SPSSODescriptor>
```
in this case entityID="https://cern.ch/login" and entityID="http://fs.liu.se/adfs/services/trust"

**Comment by leifj** [comment]
Are those not ADFSen with both IDP and SP roles?

**Comment by alexstuart** [comment]
The XPath in the issue is selecting all entities which contain an IDPSSODescriptor, and both of those entities contain an IDPSSODescriptor and an SPSSODescriptor. 

@alanbuxey If you want to select entities which are **only** IdPs, then you'd have to select those with an IDPSSODescriptor which don't have an SPSSODescriptor: `//md:EntityDescriptor[md:IDPSSODescriptor][not(md:SPSSODescriptor)]`.
